//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workforce.Data.Housing.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartment()
        {
            this.HousingData = new HashSet<HousingData>();
        }
    
        public int RoomID { get; set; }
        public int RoomNumber { get; set; }
        public int CurrentCapacity { get; set; }
        public int MaxCapacity { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public bool ActiveBit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HousingData> HousingData { get; set; }
        public virtual HousingComplex HousingComplex { get; set; }
    }
}
