//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workforce.Data.Housing.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class HousingData
    {
        public int AssociateID { get; set; }
        public System.DateTime MoveInDate { get; set; }
        public System.DateTime MoveOutDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> RoomID { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual Status Status { get; set; }
    }
}
